# Generated by Django 5.0 on 2023-12-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('file_stored', models.FileField(blank=True, upload_to='upload_files')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('otp_sent', models.IntegerField(null=True)),
                ('user_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('download_file_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.file')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pass', models.CharField(max_length=60)),
                ('user_ops_access', models.BooleanField(default=False)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.verification')),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.file')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.verification')),
            ],
        ),
        migrations.CreateModel(
            name='Logged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.verification')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.verification'),
        ),
    ]
